### ISSUE TITLE
installation configure error

### ISSUE THREAD

**Issue by mayagel** [LouisBrunner/homebrew-valgrind#11]
on macOS Monterey v:12.3.1 the got the next next error while trying to install:

configure: error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)

**Comment by ChaoII** [comment]
I have the same problem。How can I solve this error?

**Comment by xcv7864** [comment]
Same problem here.

**Comment by LouisBrunner** [comment]
M1 and macOS Big Sur and later are unsupported at the moment https://github.com/LouisBrunner/valgrind-macos/issues/19
