### ISSUE TITLE
Valgrind not available on M1

### ISSUE THREAD

**Issue by daviddallakyan2005** [LouisBrunner/homebrew-valgrind#14]
Last 15 lines from /Users/daviddallakyan/Library/Logs/Homebrew/valgrind/03.make:
fixup_macho_loadcmds.c:465:22: error: use of undeclared identifier 'x86_thread_state64_t'
                  = (x86_thread_state64_t*)(&w32s[2]);
                     ^
fixup_macho_loadcmds.c:467:36: error: no member named '__rsp' in 'struct __darwin_arm_thread_state64'; did you mean '__sp'?
               init_rsp = state64->__rsp;
                                   ^~~~~
                                   __sp
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/mach/arm/_structs.h:141:13: note: '__sp' declared here
        __uint64_t __sp;    /* Stack pointer x31 */
                   ^
7 errors generated.
make[2]: *** [fixup_macho_loadcmds] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/louisbrunner/homebrew-valgrind/issues

valgrind's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.

**Comment by LouisBrunner** [comment]
Apple Silicon is unsupported at the moment https://github.com/LouisBrunner/valgrind-macos/issues/56
