### ISSUE TITLE
Calling `sha256 "digest" => :tag` in a bottle block is deprecated

### ISSUE THREAD

**Issue by wvdgoot** [LouisBrunner/homebrew-valgrind#2]
After running `brew cleanup` this warning came up:

"Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead."

The problem is on lines 14 and 15:
```
/usr/local/Homebrew/Library/Taps/louisbrunner/homebrew-valgrind/valgrind.rb:14
/usr/local/Homebrew/Library/Taps/louisbrunner/homebrew-valgrind/valgrind.rb:15
```

**Comment by wvdgoot** [comment]
Lines 14 and 15 must be replaced with:
```
    sha256 high_sierra: "7869473ca1009d871dfcb496cc4d08e0318315d18721854ef42960b76e2ef64d"
    sha256 sierra: "5ac984d472025c7bbc081e3be88b31f709944cf924945ebe85427f00d7cca73e"
```

I can't create a PR to fix the issue myself.

**Comment by LouisBrunner** [comment]
This has now been merged.
