### ISSUE TITLE
Trying to download valgrind on macOS Catalina 10.15.3 and getting 2 errors

### ISSUE THREAD

**Issue by ancaandrei** [LouisBrunner/homebrew-valgrind#4]
Hi, 
This are the errors: 
2 errors generated.
make[3]: *** [m_syswrap/libcoregrind_amd64_darwin_a-syswrap-darwin.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

How should I proceed?
Thanks!!

**Comment by wvdgoot** [comment]
Have you followed the steps specified in the README.md?

> First, tap this repository:
> ```
> brew tap LouisBrunner/valgrind
> ```
> 
> Then, install `valgrind`:
> ```
> brew install --HEAD LouisBrunner/valgrind/valgrind
> ```
> 
> You can now use `valgrind` as normal.
> 
> ## Update
> 
> Any `brew upgrade` will now correctly rebuild the latest `LouisBrunner/valgrind` instead of the upstream one (which doesn't support latest macOS versions).
> 
> ```
> brew upgrade --fetch-HEAD LouisBrunner/valgrind/valgrind
> ```

**Comment by hadar3** [comment]
can't make it work on m1

**Comment by LouisBrunner** [comment]
@ancaandrei Do you have any more details? (thanks @wvdgoot!)

@hadar3 M1 is unsupported at the moment https://github.com/LouisBrunner/valgrind-macos/issues/19

**Comment by JJJJJoshua** [comment]
Sorry I also encounter some issue... I guess it's because of macOS Monterey.

Here is what terminal says:
```
checking for a supported version of gcc... ok (Apple LLVM version 13.0.0)
checking build system type... x86_64-pc-darwin
checking host system type... x86_64-pc-darwin
checking for a supported CPU... ok (x86_64)
checking for a 64-bit only build... yes
checking for a 32-bit only build... no
checking for a supported OS... ok (darwin)
checking for the kernel version... unsupported (21.1.0)
configure: error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/louisbrunner/homebrew-valgrind/issues

These open issues may also help:
Trying to download valgrind on macOS Catalina 10.15.3 and getting 2 errors https://github.com/LouisBrunner/homebrew-valgrind/issues/4
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

By the way, I'm using Intel chip and type the first two commands, namely 
`brew tap LouisBrunner/valgrind`
`brew install --HEAD LouisBrunner/valgrind/valgrind`

Thanks!

**Comment by mhassanameri** [comment]
>
Exactly the same for me. Is there any solution?  I really need it.

**Comment by LouisBrunner** [comment]
@JJJJJoshua @mhassanameri M1 is unsupported at the moment.

**Comment by gsq7474741** [comment]
@LouisBrunner I try to install it on macOS Monterey with intel i9 cpu, but also not work

```
configure: error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Trying to download valgrind on macOS Catalina 10.15.3 and getting 2 errors https://github.com/LouisBrunner/homebrew-valgrind/issues/4

Error: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.
```

**Comment by LouisBrunner** [comment]
@gsq7474741 Monterey is unsupported https://github.com/LouisBrunner/valgrind-macos/issues/44

**Comment by jmgomez** [comment]
Is M1 and Monterey still unsupported?

Thanks

**Comment by tristenduggan** [comment]
I'm trying to get it on Mac OS Monterey as well. Is this an option yet?

**Comment by LouisBrunner** [comment]
M1 and macOS Big Sur and later are unsupported at the moment https://github.com/LouisBrunner/valgrind-macos/issues/19
