### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by ArthurPahon** [LouisBrunner/homebrew-valgrind#6]
Hello @LouisBrunner I am on M1 Monterey 12.1 and I can't install I have this error when it makes the ./configure :

"configure: error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)"

Could you help me please ?

**Comment by mhassanameri** [comment]
The terminal on my mac also shows the following errors/output when i run "brew install --HEAD LouisBrunner/valgrind/valgrind". 

Any help or suggestion is appreciated. 


checking for perl... /usr/bin/perl
checking for gdb... /no/gdb/was/found/at/configure/time
checking dependency style of clang... none
checking for diff -u... yes
checking for xcrun... yes
checking for Xcode SDK and includes... /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk (includes: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include)
checking for a supported version of gcc... ok (Apple LLVM version 13.0.0)
checking build system type... x86_64-pc-darwin
checking host system type... x86_64-pc-darwin
checking for a supported CPU... ok (x86_64)
checking for a 64-bit only build... yes
checking for a 32-bit only build... no
checking for a supported OS... ok (darwin)
checking for the kernel version... unsupported (21.1.0)
configure: error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)

**Comment by LouisBrunner** [comment]
Neither M1 nor 12.X is supported at the moment (https://github.com/LouisBrunner/valgrind-macos/issues/44)

**Comment by dablelv** [comment]
> Hello @LouisBrunner I am on M1 Monterey 12.1 and I can't install I have this error when it makes the ./configure :
> 
> "configure: error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)"
> 
> Could you help me please ?

Hi, bro, have you solved this problem? I encountered the same problem on macOS Monterey 12.5.

**Comment by LouisBrunner** [comment]
Hi @dablelv,

As stated above, 12.X is not supported at the moment.
