### ISSUE TITLE
ERROR when trying to install Valgrind on MacOS 11.6

### ISSUE THREAD

**Issue by highonapple** [LouisBrunner/homebrew-valgrind#8]
checking for gdb... /no/gdb/was/found/at/configure/time
checking dependency style of clang... none
checking for diff -u... yes
checking for xcrun... yes
checking for Xcode SDK and includes... /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk (includes: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include)
checking for a supported version of gcc... ok (Apple LLVM version 13.0.0)
checking build system type... x86_64-pc-darwin
checking host system type... x86_64-pc-darwin
checking for a supported CPU... ok (x86_64)
checking for a 64-bit only build... yes
checking for a 32-bit only build... no
checking for a supported OS... ok (darwin)
checking for the kernel version... Darwin 20.x (20.6.0) / macOS 11 Big Sur
checking for the Xcode SDK version... unsupported (12.1)

configure: error: Valgrind works on Darwin 10.x-19.x (Mac OS X 10.6-11 and macOS 10.12-15)

**Comment by LouisBrunner** [comment]
macOS 11 and later is unsupported at the moment https://github.com/LouisBrunner/valgrind-macos/issues/44
